Repository Git21221/JS-beginner-projects, pull requests merged in 2023-10, with the labels that each got.

#10 added Js Calulator and Updated main html
  Js_Calculator/app.js
  Js_Calculator/index.html
  Js_Calculator/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 Enter button in calculator fixed work as equal to button
  Js_Calculator/app.js
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#32 Currency Converter functionality added
  Currency Converter/currency_converter.html
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#23 feat: added Game of life project
  .DS_Store
  game-of-life/.gitignore
  game-of-life/README.md
  game-of-life/package.json
  game-of-life/public/.DS_Store
  game-of-life/public/index.html
  game-of-life/public/js/index.js
  game-of-life/src/config.js
  game-of-life/src/example/glider_gun.js
  game-of-life/src/index.js
  game-of-life/webpack.config.js
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#34 feat:calender-with-days (#19)
  calender/index.html
  calender/script/script.js
  calender/style/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#50 To Do List Funtionality Added And UI Modified
  To Do List/todolist.html
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#48 12 and 24 hour format added
  Digital Clock/css/style.css
  Digital Clock/digitalClock.html
  Digital Clock/js/script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#36 Added Random Password Generator
  Random Password Generator/css/style.css
  Random Password Generator/index.html
  Random Password Generator/js/script.js
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#81 automated QR generator added
  automatedQRgenerator/QR_git.png
  automatedQRgenerator/index.html
  automatedQRgenerator/script.js
  automatedQRgenerator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#99 Add contributors to the readme file
  readme.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#115 Improved readme file
  readme.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#116 Added chatroom app
  Chatroom Application/.gitignore
  Chatroom Application/app.js
  Chatroom Application/package-lock.json
  Chatroom Application/package.json
  Chatroom Application/public/chat.html
  Chatroom Application/public/index.html
  Chatroom Application/public/index.js
  Chatroom Application/public/style.css
  Chatroom Application/utils/message.js
  Chatroom Application/utils/users.js
Labels: hacktoberfest, hacktoberfest-accepted, Feature

#117 Fixed issue #113 : todo folder
  To Do List/.gitignore
  To Do List/index.js
  To Do List/package-lock.json
  To Do List/package.json
  To Do List/public/index.html
  To Do List/public/script.js
  To Do List/public/style.css
  To Do List/tasks.json
  To Do List/todolist.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#249 linked it to the home page
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
